### PR TITLE
Added the support for post operations (DownloadStation Create with upload and FileStation Upload file)

### PR DESCRIPTION
**Pull request by Matt-Co**
I created some more methods and typically those that needs to use the Post requests.
The two methods are :
- DownloadStation Create (with file upload directly to the server)
- FileStation Upload

### CODE REVIEW

**Comment by matteobruni** [comment]
Hi, I can't merge if the build fails.
You can remove tests, I use a test project not committed for personal and security reasons to test everything.
Can you tell me more about the implementations?
For example I have seen a TaskEx folder but I don't understand why you haven't used the existing Task folder.

**Comment by Matt-Co** [comment]
Hi,
I removed the tests that need a physical host but I kept the one I created on the QueryStringManager because I found a bug on the constructor with IEnumerable parameter. (I added a Cast<string> method call). I initially wanted to modify the constructor declaration to accept only IEnumerable<string> parameters but did not wanted to cause troubles if someone is using it (except me) - it can be a breaking change.

I wrote the implementation trying to keep your architecture. But for the TaskEx, I had to create a new Request class because the api and the cgi are different from the standard one.
In the standard TaskRequest class, the inheritance hierarchy create a 'SYNO.DownloadStation.Task' api on 'webapi/DownloadStation/task.cgi'. But for this operation, the api is 'SYNO.DownloadStation2.Task' on the 'webapi/entry.cgi'.
If you think another technique is more suitable to handle these cases, I'm open to discuss it with you.

I also added comments in the code to let you understand how and why I decided to handle post messages (on SynologyConnection and SynologyRequest).

**Comment by matteobruni** [comment]
I'm thinking about creating another project for DownloadStation2 APIs, but I'm not sure.For now I can keep the Ex folder.
FileStation APIs with DSM 6.0 are not working because of 404 error but if I change the path I break with previous version.
I was thinking about checking version for APIs using the main Info but it's a future implementation.
For the merge, I think there's something broken with AppVeyor because it's not preparing the build for the branch and I opened an issue about it, i'll wait for the pr build and I will merge.

**Comment by Matt-Co** [comment]
Yes the main info would be the more robust solution to get things working every time.
But a large refactoring will be needed to handle it. 
You could also trace the parameter versions with attributes and add it or not at runtime (when requests are done) using this information.

**Comment by matteobruni** [comment]
> But a large refactoring will be needed to handle it. 
> This is the main reason why it's not implemented the Info solution, I have no time for now to implement that.

**Pull request merged**
